version: '3.10'

services:
  web:
    build: .
    command: uvicorn manage:app --host 0.0.0.0 --port 8989 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8989:8989"
    networks:
      - db_network

  postgres:
    image: postgres:14.7
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: web/.env
    restart: always
    networks:
      - db_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: web/.env
    ports:
      - "5055:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  pgadmin_data: