"""empty message

Revision ID: 30c6be1fac65
Revises: ac6615408a1d
Create Date: 2024-01-23 11:26:06.433560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30c6be1fac65"
down_revision = "ac6615408a1d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
