"""empty message

Revision ID: 8b4fbb55f3d0
Revises: 30c6be1fac65
Create Date: 2024-01-26 05:58:26.847055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b4fbb55f3d0"
down_revision = "30c6be1fac65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media", sa.Column("car_type_body", sa.String(length=500), nullable=True)
    )
    op.add_column("media", sa.Column("car_color", sa.String(length=500), nullable=True))
    op.add_column("media", sa.Column("car_brand", sa.String(length=500), nullable=True))
    op.add_column(
        "media", sa.Column("license_plate_number", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "media",
        sa.Column("license_plate_country", sa.String(length=500), nullable=True),
    )
    op.alter_column("media", "url", existing_type=sa.VARCHAR(length=500), nullable=True)
    op.drop_column("media", "result")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column("result", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "media", "url", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.drop_column("media", "license_plate_country")
    op.drop_column("media", "license_plate_number")
    op.drop_column("media", "car_brand")
    op.drop_column("media", "car_color")
    op.drop_column("media", "car_type_body")
    # ### end Alembic commands ###
