"""empty message

Revision ID: 93029f9fcb22
Revises: 8b4fbb55f3d0
Create Date: 2024-01-26 07:09:37.162874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93029f9fcb22"
down_revision = "8b4fbb55f3d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("car_type_body_score", sa.Float(), nullable=True))
    op.add_column("media", sa.Column("car_color_score", sa.Float(), nullable=True))
    op.add_column("media", sa.Column("car_brand_score", sa.Float(), nullable=True))
    op.add_column(
        "media", sa.Column("license_plate_number_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "media", sa.Column("license_plate_country_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "license_plate_country_score")
    op.drop_column("media", "license_plate_number_score")
    op.drop_column("media", "car_brand_score")
    op.drop_column("media", "car_color_score")
    op.drop_column("media", "car_type_body_score")
    # ### end Alembic commands ###
