"""empty message

Revision ID: ac6615408a1d
Revises: caa9e151f60a
Create Date: 2024-01-23 11:14:42.652054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac6615408a1d"
down_revision = "caa9e151f60a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
